apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: super-todo-production-cluster
  namespace: production
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: super-todo-production
    app.kubernetes.io/environment: production
    app.kubernetes.io/part-of: super-todo
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      work_mem: "8MB"
      maintenance_work_mem: "256MB"

  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true

  storage:
    size: 10Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
