apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: super-todo-production
  namespace: production
spec:
  interval: 15m
  chart:
    spec:
      chart: ./infrastructure/charts/super-todo
      version: "*"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Production-specific configuration - will be overridden by HPA
    replicaCount: 2

    image:
      repository: andreqko/super-todo
      tag: latest

    # Environment variables
    env:
      NODE_ENV: production
      PORT: "3000"
      # Redis configuration
      REDIS_HOST: "super-todo-production-redis-master"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://super-todo-production-redis-master:6379"
      # PostgreSQL configuration will be provided via cluster secret

    # Disable health checks for now since we don't have /health endpoint
    healthCheck:
      enabled: false

    # Production resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

    # Ingress configuration for production
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: app.local
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # Service configuration
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    # Enable HPA for production (2-5 replicas)
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    # Security context (matching your Dockerfile)
    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    # Redis configuration for production
    redis:
      enabled: true
      auth:
        enabled: false
      image:
        repository: bitnami/redis
        tag: "latest"
      master:
        persistence:
          enabled: true
          size: 2Gi
      replica:
        replicaCount: 1
      architecture: replication
      fullnameOverride: "super-todo-production-redis"

    # Database configuration - use CloudNativePG cluster secret
    database:
      useClusterSecret: true
      secretName: "super-todo-production-cluster"

    # PostgreSQL configuration for production - production-like settings
    cluster:
      enabled: true
      name: super-todo-production-cluster
      instances: 3
      externalClusters:
        - name: "please-ignore-me"
          connectionParameters:
            host: "localhost"
      postgresql:
        parameters:
          # Production optimized settings
          max_connections: "200"
          shared_buffers: "256MB"
          effective_cache_size: "1GB"
          work_mem: "8MB"
          maintenance_work_mem: "256MB"
          checkpoint_completion_target: "0.9"
          wal_buffers: "64MB"
          default_statistics_target: "500"
          random_page_cost: "1.1"
          # Performance tuning
          max_wal_size: "4GB"
          min_wal_size: "1GB"
          # Logging for production monitoring
          log_min_duration_statement: "1000"
          log_checkpoints: "on"
          log_lock_waits: "on"
      bootstrap:
        initdb:
          database: app
          owner: app
      storage:
        size: 10Gi
        storageClass: ""
      # Enable monitoring for production
      monitoring:
        enabled: true
        customQueriesConfigMap:
          - key: queries
            name: cnpg-default-monitoring
      # High availability configuration
      affinity:
        podAntiAffinityType: required
        topologyKey: kubernetes.io/hostname
