apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: super-todo-production
  namespace: production
spec:
  interval: 15m
  chart:
    spec:
      chart: ./infrastructure/charts/super-todo
      version: "*"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 2

    image:
      repository: andreqko/super-todo
      tag: latest

    env:
      NODE_ENV: production
      PORT: "3000"
      REDIS_HOST: "super-todo-production-redis-master"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://super-todo-production-redis-master:6379"

    healthCheck:
      enabled: false

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

    ingress:
      enabled: true
      className: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: app.local
          paths:
            - path: /
              pathType: Prefix
      tls: []

    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    redis:
      enabled: true
      auth:
        enabled: false
      image:
        repository: bitnami/redis
        tag: "latest"
      master:
        persistence:
          enabled: true
          size: 2Gi
      replica:
        replicaCount: 1
      architecture: replication
      fullnameOverride: "super-todo-production-redis"

    database:
      useClusterSecret: true
      secretName: "super-todo-production-cluster"

    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
