apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: super-todo-production
  namespace: production
spec:
  interval: 15m
  chart:
    spec:
      chart: ./infrastructure/charts/super-todo
      version: "*"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Production-specific configuration
    replicaCount: 3

    image:
      repository: andreqko/super-todo
      tag: latest

    # Environment variables
    env:
      NODE_ENV: production
      PORT: "3000"
      # Redis configuration
      REDIS_HOST: "super-todo-production-redis-master"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://super-todo-production-redis-master:6379"
      # PostgreSQL configuration
      DATABASE_URL: "postgresql://app:Xd4hdOTA1GEq9aUWG5jqOYA5rqk0Xnsku1DBlo8NJiye0GvkDvZMjwBMwlSry7Vk@super-todo-production-cluster-rw:5432/app"

    # Disable health checks for now since we don't have /health endpoint
    healthCheck:
      enabled: false

    # Production resource limits (larger)
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

    # Service configuration
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    # Enable autoscaling for production
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80

    # Security context (matching your Dockerfile)
    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    # Redis configuration for production
    redis:
      enabled: true
      auth:
        enabled: false
      image:
        repository: bitnami/redis
        tag: "latest"
      master:
        persistence:
          enabled: true
          size: 2Gi
      replica:
        replicaCount: 1
      architecture: replication
      fullnameOverride: "super-todo-production-redis"

    # PostgreSQL configuration for production - temporarily disabled
    # PostgreSQL configuration for production - disabled due to validation issues
    cluster:
      enabled: false
