apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-helmreleases
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux-cd/infrastructure
  prune: true
  wait: true
  resources:
    - postgres/production/helmrelease.yaml
    - postgres/staging/helmrelease.yaml
    - redis/production/helmrelease.yaml
    - redis/staging/helmrelease.yaml
