apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-production
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-cluster
      version: "9.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: true
      password: "production-secure-redis-password-change-me"
    nodes: 6
    replicas: 1
    persistence:
      enabled: true
      size: 20Gi
      storageClass: standard
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    redis:
      configuration: |
        maxmemory 1024mb
        maxmemory-policy allkeys-lru
        timeout 300
        tcp-keepalive 60
        appendonly yes
        appendfsync everysec
        save 900 1
        save 300 10
        save 60 10000
    networkPolicy:
      enabled: true
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: super-todo
            - namespaceSelector:
                matchLabels:
                  name: production
    podAntiAffinity: hard
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
