apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-cluster
      version: "9.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: true
      password: "redis-secure-password-123"
    nodes: 6
    replicas: 1
    persistence:
      enabled: true
      size: 8Gi
      storageClass: standard
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    networkPolicy:
      enabled: false
    redis:
      configuration: |
        maxmemory 512mb
        maxmemory-policy allkeys-lru
        timeout 300
        tcp-keepalive 60
  install:
    crds: create
  upgrade:
    crds: create
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: redis
  type: ClusterIP
