apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app.kubernetes.io/name: production
    app.kubernetes.io/part-of: super-todo
    environment: production
  annotations:
    description: "Production environment for super-todo application"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    pods: "100"
    services: "20"
    persistentvolumeclaims: "10"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: production
spec:
  limits:
    - max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
    - max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      type: Pod

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-default-deny
  namespace: production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-allow-internal
  namespace: production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: production
        - podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: production
        - podSelector: {}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: default
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-allow-ingress
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: super-todo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: super-todo
  namespace: production
  labels:
    app: super-todo
    environment: production

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: super-todo
  namespace: production
spec:
  rules:
    - apiGroups: [""]
      resources: ["configmaps", "secrets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["pods", "pods/logs", "endpoints"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["pods/portforward"]
      verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: super-todo
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: super-todo
subjects:
  - kind: ServiceAccount
    name: super-todo
    namespace: production

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: super-todo
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: super-todo
  unhealthyPodEvictionPolicy: IfHealthyBudget
