apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-staging
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: "18.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: true
      password: "staging-dev-redis-123"
    master:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: standard
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    metrics:
      enabled: false
    networkPolicy:
      enabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: redis-staging
  namespace: staging
  labels:
    app: redis
    environment: staging
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-staging
  type: ClusterIP
