apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-staging
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    monitoring:
      enabled: false
    podMonitorEnabled: false
  install:
    crds: create
  upgrade:
    crds: create

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-staging
  namespace: staging
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-1
  bootstrap:
    initdb:
      database: todos_db_staging
      owner: postgres
      secret:
        name: postgres-staging-credentials
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "8MB"
      default_statistics_target: "50"
      random_page_cost: "1.1"
      effective_io_concurrency: "100"
      work_mem: "655kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  storage:
    size: 5Gi
    storageClass: standard
  monitoring:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-staging-credentials
  namespace: staging
type: Opaque
stringData:
  username: postgres
  password: staging-dev-password-123

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-staging
  namespace: staging
  labels:
    app: postgres
    environment: staging
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    cnpg.io/cluster: postgres-staging
  type: ClusterIP
