apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-production
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    monitoring:
      enabled: true
    podMonitorEnabled: true
  install:
    crds: Create
  upgrade:
    crds: Create
