apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg-production
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    monitoring:
      enabled: true
    podMonitorEnabled: true
  install:
    crds: create
  upgrade:
    crds: create

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-production
  namespace: production
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-1
  bootstrap:
    initdb:
      database: todos_db_production
      owner: postgres
      secret:
        name: postgres-production-credentials
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "512MB"
      effective_cache_size: "2GB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2621kB"
      min_wal_size: "4GB"
      max_wal_size: "16GB"
      log_statement: "mod"
      log_min_duration_statement: "5000"
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
  storage:
    size: 50Gi
    storageClass: standard
  monitoring:
    enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: cnpg.io/cluster
                  operator: In
                  values:
                    - postgres-production
            topologyKey: kubernetes.io/hostname
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://super-todo-backups/postgres-production
      endpointURL: https://s3.amazonaws.com
      s3Credentials:
        accessKeyId:
          name: aws-s3-credentials
          key: access-key-id
        secretAccessKey:
          name: aws-s3-credentials
          key: secret-access-key
      wal:
        maxParallel: 4

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-production-credentials
  namespace: production
type: Opaque
stringData:
  username: postgres
  password: production-secure-password-change-me-789

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-production
  namespace: production
  labels:
    app: postgres
    environment: production
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    cnpg.io/cluster: postgres-production
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-production
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-production
  unhealthyPodEvictionPolicy: IfHealthyBudget
