apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - postgres/production/helmrelease.yaml
  - postgres/staging/helmrelease.yaml
  - redis/production/helmrelease.yaml
  - redis/staging/helmrelease.yaml

commonAnnotations:
  deployment.type: infrastructure
