apiVersion: v1
kind: ServiceAccount
metadata:
  name: super-todo
  namespace: production
  labels:
    app: super-todo
    environment: production

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: super-todo
  namespace: production
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/logs", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: super-todo
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: super-todo
subjects:
  - kind: ServiceAccount
    name: super-todo
    namespace: production

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: super-todo
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: super-todo
  unhealthyPodEvictionPolicy: IfHealthyBudget
