apiVersion: v1
kind: ServiceAccount
metadata:
  name: super-todo
  namespace: staging
  labels:
    app: super-todo
    environment: staging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: super-todo
  namespace: staging
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: super-todo
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: super-todo
subjects:
  - kind: ServiceAccount
    name: super-todo
    namespace: staging
