apiVersion: v1
kind: Service
metadata:
  name: redis-production
  namespace: production
  labels:
    app: redis
    environment: production
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: redis-production
  type: ClusterIP

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-production
  namespace: production
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
      app.kubernetes.io/instance: redis-production
  unhealthyPodEvictionPolicy: IfHealthyBudget
