apiVersion: v1
kind: Service
metadata:
  name: redis-staging
  namespace: staging
  labels:
    app: redis
    environment: staging
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-staging
  type: ClusterIP
