apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: super-todo-staging-cluster
  namespace: staging
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: super-todo-staging
    app.kubernetes.io/environment: staging
    app.kubernetes.io/part-of: super-todo
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: "64MB"
      effective_cache_size: "256MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"

  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true

  storage:
    size: 2Gi

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
