apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: super-todo-staging
  namespace: staging
spec:
  interval: 15m
  chart:
    spec:
      chart: ./infrastructure/charts/super-todo
      version: "*"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # Staging-specific configuration
    replicaCount: 1

    image:
      repository: andreqko/super-todo
      tag: latest

    # Environment variables
    env:
      NODE_ENV: staging
      PORT: "3000"
      # Redis configuration
      REDIS_HOST: "super-todo-staging-redis-master"
      REDIS_PORT: "6379"
      REDIS_URL: "redis://super-todo-staging-redis-master:6379"
      # PostgreSQL configuration will be provided via cluster secret

    # Disable health checks for now since we don't have /health endpoint
    healthCheck:
      enabled: false

    # No resource limits for staging
    resources: {}

    # Ingress configuration for staging
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: app.staging.local
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # Service configuration
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    # Security context (matching your Dockerfile)
    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    # Redis configuration for staging
    redis:
      enabled: true
      auth:
        enabled: false
      image:
        repository: bitnami/redis
        tag: "latest"
      master:
        persistence:
          enabled: false
      replica:
        replicaCount: 0
      architecture: standalone
      fullnameOverride: "super-todo-staging-redis"

    # Database configuration - use CloudNativePG cluster secret
    database:
      useClusterSecret: true
      secretName: "super-todo-staging-cluster"

    # PostgreSQL configuration for staging - single instance, no replication
    cluster:
      enabled: true
      name: super-todo-staging-cluster
      instances: 1
      externalClusters:
        - name: "please-ignore-me"
          connectionParameters:
            host: "localhost"
      postgresql:
        parameters:
          # Development/staging optimized settings
          max_connections: "50"
          shared_buffers: "64MB"
          effective_cache_size: "256MB"
          work_mem: "4MB"
          maintenance_work_mem: "64MB"
          checkpoint_completion_target: "0.7"
          wal_buffers: "16MB"
          default_statistics_target: "100"
          random_page_cost: "1.1"
      bootstrap:
        initdb:
          database: app
          owner: app
      storage:
        size: 2Gi
        storageClass: ""
      # Minimal monitoring for staging
      monitoring:
        enabled: false
